# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expose the port Flask uses
EXPOSE 10000

# Run using gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:10000", "Road_Anomaly_Detection:app"]
